services:
  backend:
    image: gprime44/helper-backend:latest
    ports:
      - "8080:8080"
    volumes:
      - backend_data:/app/data
    environment:
      SPRING_DATASOURCE_URL: jdbc:sqlite:data/brassam.db
      SPRING_LIQUIBASE_ENABLED: "true"
      ALLOWED_ORIGINS: "http://your-production-domain.com"

  frontend:
    image: gprime44/helper-frontend:latest
    ports:
      - "80:80"
    environment:
      - VITE_API_URL=http://localhost:8080
    depends_on:
      - backend

volumes:
  backend_data:
