spring:
  application:
    name: brassam-helper
  datasource:
    url: jdbc:mariadb://localhost:3306/brassam
    username: root
    password: password
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
