spring:
  application:
    name: brassam-helper
  datasource:
    url: jdbc:sqlite:data/brassam.db
    driver-class-name: org.sqlite.JDBC
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.community.dialect.SQLiteDialect
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml

app:
  security:
    allowed-origins: ${ALLOWED_ORIGINS:}
