spring:
  application:
    name: brassam-helper
  datasource:
    url: jdbc:sqlite:data/brassam.db
    driver-class-name: org.sqlite.JDBC
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.community.dialect.SQLiteDialect
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml

app:
  security:
    jwt:
      secret: ${JWT_SECRET:votre_cle_secrete_tres_longue_et_secure_pour_le_dev_un_minimum_de_32_caracteres}
      expiration: 86400000 # 24 heures
